# Generated by Django 3.2.6 on 2021-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=16, null=True, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('imdb_rating', models.SmallIntegerField()),
                ('imdb_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=16)),
                ('copy_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddConstraint(
            model_name='filmcopy',
            constraint=models.UniqueConstraint(fields=('location', 'copy_id'), name='Unique copies'),
        ),
    ]
