# Generated by Django 3.2.6 on 2021-08-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('year', models.SmallIntegerField()),
                ('imdb_rating', models.SmallIntegerField()),
                ('imdb_votes', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=16)),
                ('copy_id', models.CharField(max_length=64)),
                ('raw_title', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('year', models.SmallIntegerField(null=True)),
                ('ean', models.CharField(max_length=16, null=True)),
                ('image_url', models.URLField(null=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.film')),
            ],
            options={
                'verbose_name_plural': 'Film copies',
            },
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.UniqueConstraint(fields=('title', 'year'), name='Unique films'),
        ),
        migrations.AddConstraint(
            model_name='filmcopy',
            constraint=models.UniqueConstraint(fields=('location', 'copy_id'), name='Unique copies'),
        ),
    ]
