# Generated by Django 3.2.6 on 2021-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
